import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { access, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import test from "node:test";
const execFileAsync=promisify(execFile),SCRIPT=path.resolve(import.meta.dirname,"../scripts/route-company-skills.mjs"),CASES=path.resolve(import.meta.dirname,"company-skill-routing-cases.json"),COMPARE=path.resolve(import.meta.dirname,"../../../docs/skills");
const SKILLS=[["fe-ai-test","ai-test","生成 Midscene 测试文件 midscene-test.ts、自动化测试用例和报告。"],["fe-gen-frontend-plan","gen-frontend-plan","从原型、OpenAPI、PageCenter 和 Figma UI Meta 生成 docs/plan 前端方案。"],["fe-gen-code","gen-code","生成活动前端页面、组件和业务逻辑代码。"],["fe-figma-analyze","figma-analyze","分析 Figma 原型并输出交互 Markdown 方案。"],["figma-analyze","figma-analyze","分析 Figma 原型并输出交互 Markdown 方案。"],["fe-figma-to-ui-meta","figma-to-ui-meta","调用 Mercury 将 Figma 转成 figma-ui-meta.json。"],["fe-gen-page-center-config","gen-page-center-config","生成 page-center-config.json 并推送配置。"],["fe-custom-components-skill","custom-components-skill","生成根据 uiMeta 渲染的活动积木组件。"],["fe-ui2-upgrade-guide","ui2-upgrade-guide","将 ui-components 升级到 ui2-components。"],["fe-gen-service","gen-service","从 OpenAPI 生成 TypeScript service。"]];
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),"ai-talk-mvp-"));for(const[d,n,s]of SKILLS){const p=path.join(root,".agents","skills",d);await mkdir(p,{recursive:true});await writeFile(path.join(p,"SKILL.md"),`---\nname: ${n}\ndescription: '${s}'\n---\nBODY_MUST_NOT_BE_READ\n`);}return root;}
async function route(root,c,...extra){const a=[SCRIPT,"--root",root,"--query",c.prompt];for(const e of c.evidence_types||[])a.push("--evidence-type",e);a.push(...extra);return JSON.parse((await execFileAsync(process.execPath,a,{encoding:"utf8"})).stdout);}
function matrix(rs){const m={};for(const r of rs){m[r.expected]||={};m[r.expected][r.predicted||"NONE"]=(m[r.expected][r.predicted||"NONE"]||0)+1;}return m;}
test("real index reports duplicate names and excludes comparison copies",async t=>{const root=await fixture();t.after(()=>rm(root,{recursive:true,force:true}));const p=await route(root,{prompt:"分析 Figma 原型并输出 Markdown 文档"},"--source-root",`comparison=${COMPARE}`);assert.equal(p.index.stats.by_scope.project.unique_names,9);assert.deepEqual(p.index.duplicate_name_conflicts.map(x=>x.name),["figma-analyze"]);assert.ok(p.index.warnings.some(x=>x.includes("Excluded non-runtime")));for(const x of[p.recommendation,...p.alternatives].filter(Boolean)){await access(x.path);assert.ok(!x.path.startsWith(COMPARE));}});
test("indexes explicit applicability sections but ignores ordinary body",async t=>{const root=await mkdtemp(path.join(os.tmpdir(),"ai-talk-applicability-"));t.after(()=>rm(root,{recursive:true,force:true}));const allowed=path.join(root,".agents","skills","allowed"),ignored=path.join(root,".agents","skills","ignored");await mkdir(allowed,{recursive:true});await mkdir(ignored,{recursive:true});await writeFile(path.join(allowed,"SKILL.md"),"---\nname: allowed-router\ndescription: 公司发布辅助。\n---\n## 适用场景\n星河\n");await writeFile(path.join(ignored,"SKILL.md"),"---\nname: ignored-router\ndescription: 通用辅助。\n---\n普通正文包含星河，但不得索引。\n");const p=await route(root,{prompt:"星河"});assert.equal(p.recommendation.name,"allowed-router");assert.ok(![p.recommendation,...p.alternatives].filter(Boolean).some(x=>x.name==="ignored-router"));});
test("benchmark prints confusion matrix and errors and meets thresholds",async t=>{const root=await fixture();t.after(()=>rm(root,{recursive:true,force:true}));const cs=JSON.parse(await readFile(CASES,"utf8")),rs=await Promise.all(cs.map(async c=>{const p=await route(root,c),top3=[p.recommendation,...p.alternatives].filter(Boolean).map(x=>x.name);return{id:c.id,clarity:c.clarity,expected:c.expected_skill,predicted:top3[0]||null,top3};})),clear=rs.filter(x=>x.clarity==="clear"),amb=rs.filter(x=>x.clarity==="ambiguous"),top1=clear.filter(x=>x.predicted===x.expected).length/clear.length,top3=amb.filter(x=>x.top3.includes(x.expected)).length/amb.length,errors=rs.filter(x=>x.clarity==="clear"?x.predicted!==x.expected:!x.top3.includes(x.expected));process.stdout.write(JSON.stringify({benchmark:{total:rs.length,clear_top1_accuracy:top1,ambiguous_top3_recall:top3},confusion_matrix:matrix(rs),errors},null,2)+"\n");assert.ok(cs.length>=20);assert.ok(top1>=.9,`Top1 ${top1}`);assert.ok(top3>=.9,`Top3 ${top3}`);});
test("generic page test does not select ai-test",async t=>{const root=await fixture();t.after(()=>rm(root,{recursive:true,force:true}));const p=await route(root,{prompt:"这个活动页面测一下，看看布局和按钮"});assert.equal(p.recommendation.name,"ui-self-check");assert.equal(p.retrieval_profile.desired_output,"live_ui_findings");assert.deepEqual(Object.keys(p.retrieval_profile).sort(),["desired_output","evidence_types","exclusion_terms","execution_mode","intent_terms","target_category","task_action","unknowns"]);assert.ok(p.expanded_terms.length>0);});
